### ISSUE TITLE
"Animated Node with tag2 does not exist"  - Error Message while running App in Emulator

### ISSUE THREAD

**Issue by RohitSreekumar1994** [EarlGeorge/timetable#6]
Hi,

While trying to run the app in an emulator, I am getting the below error. 
Could you please check.

![image](https://user-images.githubusercontent.com/38423210/121526270-82987000-c9f9-11eb-8f88-731b7cf8cccf.png)

Thanks,
Rohit

**Comment by EarlGeorge** [comment]
Try reinstalling it with: expo install

Or try to downgrade react-native and expo sdk package to older version. @RohitSreekumar1994

**Comment by RohitSreekumar1994** [comment]
Hi Earl,

Its resolved after downgrading the react-native version

Thanks,
Rohit
